
# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# See http://travis-ci.org/ for details
language: python

before_install:
 - sudo apt-get install -y python-virtualenv
 - virtualenv planemo-venv
 - . planemo-venv/bin/activate
 - pip install planemo

script:
 - planemo lint ${TRAVIS_BUILD_DIR}/galaxy/probmetab
 - travis_wait 40 planemo test --galaxy_branch release_18.05 --no_cache_galaxy ${TRAVIS_BUILD_DIR}/galaxy/probmetab


